CREATE DATABASE QLBH
GO

CREATE TABLE NHAN_VIEN(
    MaNV CHAR(4) PRIMARY KEY,
    TenNV NVARCHAR(100),
    ChucVu NVARCHAR(100),
    TimeCreated DATETIME,
    TimeUpdated DATETIME,
	PassWordNV NVARCHAR(50)
);
GO

CREATE TABLE DON_HANG(
    MaDH CHAR(6) PRIMARY KEY,
    STT INT,
    ThoiGianNhap DATETIME,
    NvNhap CHAR(4) FOREIGN KEY REFERENCES NHAN_VIEN(MaNV),
    TongTien INT,
    TienNhan INT,
    TienThoi INT
);
GO

CREATE TABLE LOAISP(
    MaLoaiSP NVARCHAR(6) PRIMARY KEY,
    TenLoaiSP NVARCHAR(100),
    KieuSP NVARCHAR(50),
    TimeCreated DATETIME,
    TimeUpdated DATETIME
);
GO

CREATE TABLE SANPHAM(
    MaSP NVARCHAR(8) PRIMARY KEY,
    TenSP NVARCHAR(100),
    LOAI NVARCHAR(6) FOREIGN KEY REFERENCES LoaiSP(MaLoaiSP),
    GiaMua INT,
	avatar NVARCHAR(50),
    TinhTrang NVARCHAR(20),
    isDelete BIT,
    isNew BIT,
    TimeCreated DATETIME,
    TimeUpdated DATETIME
);
GO

CREATE TABLE SP_TrungBay(
    MaSP NVARCHAR(8) FOREIGN KEY REFERENCES SANPHAM(MaSP),
    GiaBan INT,
    TinhTrang NVARCHAR(20),
    TimeCreated DATETIME,
    TimeUpdated DATETIME,
    PRIMARY KEY (MaSP)
);
GO

CREATE TABLE DONHANG_SP(
     MaDH CHAR(6) FOREIGN KEY REFERENCES DON_HANG(MaDH),
     MaSP NVARCHAR(8) FOREIGN KEY REFERENCES SANPHAM(MaSP),
     GiaBan INT,
     SoLuong INT,
    CONSTRAINT KhoaDonHang PRIMARY KEY (MaDH, MaSP)
);
GO